from bdd.db_functions import serialized_player
from bdd.db_functions import deserialized_table_players
from bdd.db_functions import serialized_tournament
from bdd.db_functions import deserialized_table_tournament